# Fly.io app configuration (replace app name after `fly launch`)
app = "openai-observability" # change to your actual app name
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = 3000
  PROBE_INTERVAL_SEC = 1800
  OPENAI_MODEL = "gpt-4.1-nano"
  OPENAI_RESPONSES_MODEL = "gpt-4o-mini"
  OPENAI_EMBEDDINGS_MODEL="text-embedding-3-small"
  PROBE_REGION = "us-west-1"
  ENABLE_DB = 1
  DB_FILE = "/data/data.db"
  HTTP_TIMEOUT_MS = 12000
  PROBE_MODE = "all"
  LOG_SIM_ENABLED = 0
  LOG_SIM_INTERVAL_MS = 30000
  EMB_INDEX_INTERVAL_MS = 45000

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[mounts]
  source = "data"
  destination = "/data"
