# Fly.io app configuration (replace app name after `fly launch`)
app = "openai-status-lite" # change to your actual app name
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"
  PROBE_INTERVAL_SEC = "60"
  OPENAI_MODEL = "gpt-4o-mini"
  PROBE_REGION = "us-west-1"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
